### PR TITLE
Do not display help when deleting all pods/containers

### LINKED ISSUE #1144: 'crictl rm(p) -af' display help when there is nothing to delete
#### What happened:
Using
```
crictl rmp -af
crictl rm -af
```
display the help menu when there are no containers/pods left to delete

#### What you expected to happen:
either display nothing or a message saying that there is nothing to delete

#### How to reproduce it (as minimally and precisely as possible):
run `crictl rm -af` twice

#### Environment:

- Container runtime or hardware configuration: containerd 1.7.0 / crictl 1.26.0

### PR DESCRIPTION
**Pull request by champtar**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Running `crictl rmp -a` or `crictl rm -a` with nothing to delete was displaying the help text instead of saying that there was nothing to delete.

#### Which issue(s) this PR fixes:
Fixes #1144

#### Does this PR introduce a user-facing change?
```release-note
'crictl rm(p) -a' now properly says when there is no containers/pods to delete instead of displaying help text
```

### CODE REVIEW

File: cmd/crictl/container.go [hunk 1]
```diff
@@ -351,7 +351,12 @@ var removeContainerCommand = &cli.Command{
 		}
```
Comment (SergeyKanzhelev) [inline cmd/crictl/container.go:352]: should images show help in here: https://github.com/kubernetes-sigs/cri-tools/blob/cd4612fba769342cdde32cdc32ce817103645b90/cmd/crictl/image.go#L396 for consistency?

File: cmd/crictl/container.go [hunk 2]
```diff
@@ -351,7 +351,12 @@ var removeContainerCommand = &cli.Command{
...
 
 		if len(ids) == 0 {
-			return cli.ShowSubcommandHelp(ctx)
+			if ctx.Bool("all") {
+				logrus.Info("No containers to remove")
+				return nil
+			} else {
+				return cli.ShowSubcommandHelp(ctx)
```
Comment (SergeyKanzhelev) [inline cmd/crictl/container.go:358]: maybe add a test case to https://github.com/kubernetes-sigs/cri-tools/blob/master/test/e2e/help_test.go

File: cmd/crictl/container.go (hunk 1 above)
Comment (champtar) [reply cmd/crictl/container.go:352]: Done

File: cmd/crictl/container.go (hunk 2 above)
Comment (champtar) [reply cmd/crictl/container.go:358]: done but not tested (let see if the CI is happy)

Comment (SergeyKanzhelev) [reply cmd/crictl/container.go:358]: yeah, likely need to start crio or something before calling in

**Comment by champtar** [comment]
@SergeyKanzhelev CI is good now, tell me if the tests changes are too intrusive

File: cmd/crictl/container.go [hunk 3]
```diff
@@ -351,7 +351,12 @@ var removeContainerCommand = &cli.Command{
 		}
 
 		if len(ids) == 0 {
-			return cli.ShowSubcommandHelp(ctx)
+			if ctx.Bool("all") {
+				logrus.Info("No containers to remove")
+				return nil
```
Comment (haircommander) [inline cmd/crictl/container.go:356]: nit: since we return here, we don't need the `else` below.

Comment (champtar) [reply cmd/crictl/container.go:356]: you want me to change all `if A return B else return C` ? not used to the style you recommend but I don't really have preferences

Comment (haircommander) [reply cmd/crictl/container.go:356]: yeah please do, its a style preference of mine, thanks :)

Comment (champtar) [reply cmd/crictl/container.go:356]: done

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
Thank you!
